### ISSUE TITLE
InternalServerError: 500 Internal error encountered. (POST https://logging.googleapis.com/v2/entries:write)

### ISSUE THREAD

**Issue by maxbbraun** [maxbbraun/trump2cash#12]
Happening occasionally.

```
Traceback (most recent call last):
  File "/home/max_braun/trump2cash/twitter.py", line 174, in process_queue
    self.handle_data(logs, data)
  File "/home/max_braun/trump2cash/twitter.py", line 226, in handle_data
    (screen_name, user_id_str))
  File "/home/max_braun/trump2cash/logs.py", line 38, in debug
    self.logger.log_text(text, severity="DEBUG")
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 192, in log_text
    client.logging_api.write_entries([entry_resource])
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_http.py", line 165, in write_entries
    data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 335, in api_request
    error_info=method + ' ' + url)
InternalServerError: 500 Internal error encountered. (POST https://logging.googleapis.com/v2/entries:write)
```

**Comment by maxbbraun** [comment]
Happens about 7 times a week and is caught by main restart loop.

**Comment by maxbbraun** [comment]
Let's see how well https://github.com/maxbbraun/trump2cash/commit/1719b0fb5ccccfac3cb3195308039c53efa571d3 handles this.
