### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by maxbbraun** [maxbbraun/trump2cash#15]
Seeing this occasionally. Probably the same as https://github.com/tweepy/tweepy/issues/576. Could try using [tweepy from head](https://github.com/tweepy/tweepy.git) instead of the latest in PyPI ([3.5.0](https://pypi.python.org/pypi/tweepy/3.5.0)).

```
Traceback (most recent call last):
  File "/home/max_braun/trump2cash/main.py", line 34, in <module>
    twitter.start_streaming(twitter_callback)
  File "/home/max_braun/trump2cash/twitter.py", line 59, in start_streaming
    twitter_stream.filter(follow=[TRUMP_USER_ID])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 294, in _run
    raise exception
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by maxbbraun** [comment]
Happens about twice a week and is caught by the main restart loop.
